/*
 * 42videobricks
 * 42videobricks is a Video Platform As A Service (VPaaS)
 *
 * The version of the OpenAPI document: 1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.api42videobricks.client.api;

import com.api42videobricks.client.ApiException;
import com.api42videobricks.client.models.DataVideoUsageList;
import com.api42videobricks.client.models.Error;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DataApi
 */
@Disabled
public class DataApiTest {

    private final DataApi api = new DataApi();

    /**
     * List Video Usage KPIs
     *
     * Return the usage of the platform ressources.  By default, it returns monthly usage but unit (dayly|week|month) can be defined. For current period, usage is calculated until current time. Start and end dates can be also optionaly defined to filter results.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getDataVideoUsageTest() throws ApiException {
        Integer limit = null;
        Integer offset = null;
        String interval = null;
        String startDate = null;
        String endDate = null;
        DataVideoUsageList response = api.getDataVideoUsage(limit, offset, interval, startDate, endDate);
        // TODO: test validations
    }

}
