/*
 * 42videobricks
 * 42videobricks is a Video Platform As A Service (VPaaS)
 *
 * The version of the OpenAPI document: 1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.api42videobricks.client.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DataVideoUsage
 */
public class DataVideoUsageTest {
    private final DataVideoUsage model = new DataVideoUsage();

    /**
     * Model tests for DataVideoUsage
     */
    @Test
    public void testDataVideoUsage() {
        // TODO: test DataVideoUsage
    }

    /**
     * Test the property 'monthId'
     */
    @Test
    public void monthIdTest() {
        // TODO: test monthId
    }

    /**
     * Test the property 'transcoding'
     */
    @Test
    public void transcodingTest() {
        // TODO: test transcoding
    }

    /**
     * Test the property 'hosting'
     */
    @Test
    public void hostingTest() {
        // TODO: test hosting
    }

    /**
     * Test the property 'delivery'
     */
    @Test
    public void deliveryTest() {
        // TODO: test delivery
    }

    /**
     * Test the property 'drm'
     */
    @Test
    public void drmTest() {
        // TODO: test drm
    }

}
