/*
 * 42videobricks
 * 42videobricks is a Video Platform As A Service (VPaaS)
 *
 * The version of the OpenAPI document: 1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.api42videobricks.client.models;

import com.api42videobricks.client.models.VideoMultipartUploadInitResponsePartsInner;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for VideoMultipartUploadInitResponse
 */
public class VideoMultipartUploadInitResponseTest {
    private final VideoMultipartUploadInitResponse model = new VideoMultipartUploadInitResponse();

    /**
     * Model tests for VideoMultipartUploadInitResponse
     */
    @Test
    public void testVideoMultipartUploadInitResponse() {
        // TODO: test VideoMultipartUploadInitResponse
    }

    /**
     * Test the property 'chunkSize'
     */
    @Test
    public void chunkSizeTest() {
        // TODO: test chunkSize
    }

    /**
     * Test the property 'fileId'
     */
    @Test
    public void fileIdTest() {
        // TODO: test fileId
    }

    /**
     * Test the property 'fileKey'
     */
    @Test
    public void fileKeyTest() {
        // TODO: test fileKey
    }

    /**
     * Test the property 'parts'
     */
    @Test
    public void partsTest() {
        // TODO: test parts
    }

}
