/*
 * 42videobricks
 * 42videobricks is a Video Platform As A Service (VPaaS)
 *
 * The version of the OpenAPI document: 1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.api42videobricks.client.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.net.URI;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for VideoUploadInitResponse
 */
public class VideoUploadInitResponseTest {
    private final VideoUploadInitResponse model = new VideoUploadInitResponse();

    /**
     * Model tests for VideoUploadInitResponse
     */
    @Test
    public void testVideoUploadInitResponse() {
        // TODO: test VideoUploadInitResponse
    }

    /**
     * Test the property 'signedUrl'
     */
    @Test
    public void signedUrlTest() {
        // TODO: test signedUrl
    }

}
