/*
 * 42videobricks
 * 42videobricks is a Video Platform As A Service (VPaaS)
 *
 * The version of the OpenAPI document: 1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.api42videobricks.client.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for VideoMultipartUploadFinalizePartsInner
 */
public class VideoMultipartUploadFinalizePartsInnerTest {
    private final VideoMultipartUploadFinalizePartsInner model = new VideoMultipartUploadFinalizePartsInner();

    /**
     * Model tests for VideoMultipartUploadFinalizePartsInner
     */
    @Test
    public void testVideoMultipartUploadFinalizePartsInner() {
        // TODO: test VideoMultipartUploadFinalizePartsInner
    }

    /**
     * Test the property 'partNumber'
     */
    @Test
    public void partNumberTest() {
        // TODO: test partNumber
    }

    /**
     * Test the property 'etag'
     */
    @Test
    public void etagTest() {
        // TODO: test etag
    }

}
