/*
 * 42videobricks
 * 42videobricks is a Video Platform As A Service (VPaaS)
 *
 * The version of the OpenAPI document: 1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.api42videobricks.client.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for VideoAttachment
 */
public class VideoAttachmentTest {
    private final VideoAttachment model = new VideoAttachment();

    /**
     * Model tests for VideoAttachment
     */
    @Test
    public void testVideoAttachment() {
        // TODO: test VideoAttachment
    }

    /**
     * Test the property 'videoId'
     */
    @Test
    public void videoIdTest() {
        // TODO: test videoId
    }

    /**
     * Test the property 'attachmentType'
     */
    @Test
    public void attachmentTypeTest() {
        // TODO: test attachmentType
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'locale'
     */
    @Test
    public void localeTest() {
        // TODO: test locale
    }

}
