/*
 * 42videobricks
 * 42videobricks is a Video Platform As A Service (VPaaS)
 *
 * The version of the OpenAPI document: 1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.api42videobricks.client.models;

import java.util.Objects;
import com.api42videobricks.client.models.VideoMultipartUploadFinalizePartsInner;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.api42videobricks.client.JSON;

/**
 * Video Multipart upload finalization
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-11-28T10:12:12.471947Z[Etc/UTC]")
public class VideoMultipartUploadFinalize {
  public static final String SERIALIZED_NAME_FILE_ID = "fileId";
  @SerializedName(SERIALIZED_NAME_FILE_ID)
  private String fileId;

  public static final String SERIALIZED_NAME_FILE_KEY = "fileKey";
  @SerializedName(SERIALIZED_NAME_FILE_KEY)
  private String fileKey;

  public static final String SERIALIZED_NAME_PARTS = "parts";
  @SerializedName(SERIALIZED_NAME_PARTS)
  private List<VideoMultipartUploadFinalizePartsInner> parts = new ArrayList<>();

  public VideoMultipartUploadFinalize() {
  }

  public VideoMultipartUploadFinalize fileId(String fileId) {
    this.fileId = fileId;
    return this;
  }

   /**
   * file id
   * @return fileId
  **/
  @javax.annotation.Nonnull
  public String getFileId() {
    return fileId;
  }

  public void setFileId(String fileId) {
    this.fileId = fileId;
  }


  public VideoMultipartUploadFinalize fileKey(String fileKey) {
    this.fileKey = fileKey;
    return this;
  }

   /**
   * file key
   * @return fileKey
  **/
  @javax.annotation.Nonnull
  public String getFileKey() {
    return fileKey;
  }

  public void setFileKey(String fileKey) {
    this.fileKey = fileKey;
  }


  public VideoMultipartUploadFinalize parts(List<VideoMultipartUploadFinalizePartsInner> parts) {
    this.parts = parts;
    return this;
  }

  public VideoMultipartUploadFinalize addPartsItem(VideoMultipartUploadFinalizePartsInner partsItem) {
    if (this.parts == null) {
      this.parts = new ArrayList<>();
    }
    this.parts.add(partsItem);
    return this;
  }

   /**
   * Get parts
   * @return parts
  **/
  @javax.annotation.Nonnull
  public List<VideoMultipartUploadFinalizePartsInner> getParts() {
    return parts;
  }

  public void setParts(List<VideoMultipartUploadFinalizePartsInner> parts) {
    this.parts = parts;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VideoMultipartUploadFinalize videoMultipartUploadFinalize = (VideoMultipartUploadFinalize) o;
    return Objects.equals(this.fileId, videoMultipartUploadFinalize.fileId) &&
        Objects.equals(this.fileKey, videoMultipartUploadFinalize.fileKey) &&
        Objects.equals(this.parts, videoMultipartUploadFinalize.parts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fileId, fileKey, parts);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VideoMultipartUploadFinalize {\n");
    sb.append("    fileId: ").append(toIndentedString(fileId)).append("\n");
    sb.append("    fileKey: ").append(toIndentedString(fileKey)).append("\n");
    sb.append("    parts: ").append(toIndentedString(parts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("fileId");
    openapiFields.add("fileKey");
    openapiFields.add("parts");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("fileId");
    openapiRequiredFields.add("fileKey");
    openapiRequiredFields.add("parts");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to VideoMultipartUploadFinalize
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!VideoMultipartUploadFinalize.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in VideoMultipartUploadFinalize is not found in the empty JSON string", VideoMultipartUploadFinalize.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!VideoMultipartUploadFinalize.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `VideoMultipartUploadFinalize` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : VideoMultipartUploadFinalize.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("fileId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `fileId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("fileId").toString()));
      }
      if (!jsonObj.get("fileKey").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `fileKey` to be a primitive type in the JSON string but got `%s`", jsonObj.get("fileKey").toString()));
      }
      // ensure the json data is an array
      if (!jsonObj.get("parts").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `parts` to be an array in the JSON string but got `%s`", jsonObj.get("parts").toString()));
      }

      JsonArray jsonArrayparts = jsonObj.getAsJsonArray("parts");
      // validate the required field `parts` (array)
      for (int i = 0; i < jsonArrayparts.size(); i++) {
        VideoMultipartUploadFinalizePartsInner.validateJsonElement(jsonArrayparts.get(i));
      };
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!VideoMultipartUploadFinalize.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'VideoMultipartUploadFinalize' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<VideoMultipartUploadFinalize> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(VideoMultipartUploadFinalize.class));

       return (TypeAdapter<T>) new TypeAdapter<VideoMultipartUploadFinalize>() {
           @Override
           public void write(JsonWriter out, VideoMultipartUploadFinalize value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public VideoMultipartUploadFinalize read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of VideoMultipartUploadFinalize given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of VideoMultipartUploadFinalize
  * @throws IOException if the JSON string is invalid with respect to VideoMultipartUploadFinalize
  */
  public static VideoMultipartUploadFinalize fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, VideoMultipartUploadFinalize.class);
  }

 /**
  * Convert an instance of VideoMultipartUploadFinalize to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

