/*
 * 42videobricks
 * 42videobricks is a Video Platform As A Service (VPaaS)
 *
 * The version of the OpenAPI document: 1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.api42videobricks.client.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.net.URI;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.api42videobricks.client.JSON;

/**
 * Video Assets Object
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-10-27T13:34:32.692073Z[Etc/UTC]")
public class VideoAssets {
  public static final String SERIALIZED_NAME_THUMBNAIL = "thumbnail";
  @SerializedName(SERIALIZED_NAME_THUMBNAIL)
  private URI thumbnail;

  public static final String SERIALIZED_NAME_PLAYER = "player";
  @SerializedName(SERIALIZED_NAME_PLAYER)
  private URI player;

  public static final String SERIALIZED_NAME_STREAM = "stream";
  @SerializedName(SERIALIZED_NAME_STREAM)
  private URI stream;

  public static final String SERIALIZED_NAME_IFRAME = "iframe";
  @SerializedName(SERIALIZED_NAME_IFRAME)
  private String iframe;

  public VideoAssets() {
  }

  public VideoAssets thumbnail(URI thumbnail) {
    
    this.thumbnail = thumbnail;
    return this;
  }

   /**
   * Url of the video thumbnail (cann be empty ?)
   * @return thumbnail
  **/
  @javax.annotation.Nullable
  public URI getThumbnail() {
    return thumbnail;
  }


  public void setThumbnail(URI thumbnail) {
    this.thumbnail = thumbnail;
  }


  public VideoAssets player(URI player) {
    
    this.player = player;
    return this;
  }

   /**
   * Url to the video player code
   * @return player
  **/
  @javax.annotation.Nullable
  public URI getPlayer() {
    return player;
  }


  public void setPlayer(URI player) {
    this.player = player;
  }


  public VideoAssets stream(URI stream) {
    
    this.stream = stream;
    return this;
  }

   /**
   * Url to the video player stream
   * @return stream
  **/
  @javax.annotation.Nullable
  public URI getStream() {
    return stream;
  }


  public void setStream(URI stream) {
    this.stream = stream;
  }


  public VideoAssets iframe(String iframe) {
    
    this.iframe = iframe;
    return this;
  }

   /**
   * html code to integrate the player in an iframe
   * @return iframe
  **/
  @javax.annotation.Nullable
  public String getIframe() {
    return iframe;
  }


  public void setIframe(String iframe) {
    this.iframe = iframe;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VideoAssets videoAssets = (VideoAssets) o;
    return Objects.equals(this.thumbnail, videoAssets.thumbnail) &&
        Objects.equals(this.player, videoAssets.player) &&
        Objects.equals(this.stream, videoAssets.stream) &&
        Objects.equals(this.iframe, videoAssets.iframe);
  }

  @Override
  public int hashCode() {
    return Objects.hash(thumbnail, player, stream, iframe);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VideoAssets {\n");
    sb.append("    thumbnail: ").append(toIndentedString(thumbnail)).append("\n");
    sb.append("    player: ").append(toIndentedString(player)).append("\n");
    sb.append("    stream: ").append(toIndentedString(stream)).append("\n");
    sb.append("    iframe: ").append(toIndentedString(iframe)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("thumbnail");
    openapiFields.add("player");
    openapiFields.add("stream");
    openapiFields.add("iframe");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to VideoAssets
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!VideoAssets.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in VideoAssets is not found in the empty JSON string", VideoAssets.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!VideoAssets.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `VideoAssets` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("thumbnail") != null && !jsonObj.get("thumbnail").isJsonNull()) && !jsonObj.get("thumbnail").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `thumbnail` to be a primitive type in the JSON string but got `%s`", jsonObj.get("thumbnail").toString()));
      }
      if ((jsonObj.get("player") != null && !jsonObj.get("player").isJsonNull()) && !jsonObj.get("player").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `player` to be a primitive type in the JSON string but got `%s`", jsonObj.get("player").toString()));
      }
      if ((jsonObj.get("stream") != null && !jsonObj.get("stream").isJsonNull()) && !jsonObj.get("stream").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `stream` to be a primitive type in the JSON string but got `%s`", jsonObj.get("stream").toString()));
      }
      if ((jsonObj.get("iframe") != null && !jsonObj.get("iframe").isJsonNull()) && !jsonObj.get("iframe").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `iframe` to be a primitive type in the JSON string but got `%s`", jsonObj.get("iframe").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!VideoAssets.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'VideoAssets' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<VideoAssets> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(VideoAssets.class));

       return (TypeAdapter<T>) new TypeAdapter<VideoAssets>() {
           @Override
           public void write(JsonWriter out, VideoAssets value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public VideoAssets read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of VideoAssets given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of VideoAssets
  * @throws IOException if the JSON string is invalid with respect to VideoAssets
  */
  public static VideoAssets fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, VideoAssets.class);
  }

 /**
  * Convert an instance of VideoAssets to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

