/*
 * 42videobricks
 * 42videobricks is a Video Platform As A Service (VPaaS)
 *
 * The version of the OpenAPI document: 1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.api42videobricks.client.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.net.URI;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.api42videobricks.client.JSON;

/**
 * part signed url object
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-10-27T13:34:32.692073Z[Etc/UTC]")
public class VideoMultipartUploadInitResponsePartsInner {
  public static final String SERIALIZED_NAME_SIGNED_URL = "signedUrl";
  @SerializedName(SERIALIZED_NAME_SIGNED_URL)
  private URI signedUrl;

  public static final String SERIALIZED_NAME_PART_NUMBER = "PartNumber";
  @SerializedName(SERIALIZED_NAME_PART_NUMBER)
  private Integer partNumber;

  public VideoMultipartUploadInitResponsePartsInner() {
  }

  public VideoMultipartUploadInitResponsePartsInner signedUrl(URI signedUrl) {
    
    this.signedUrl = signedUrl;
    return this;
  }

   /**
   * part signed url
   * @return signedUrl
  **/
  @javax.annotation.Nullable
  public URI getSignedUrl() {
    return signedUrl;
  }


  public void setSignedUrl(URI signedUrl) {
    this.signedUrl = signedUrl;
  }


  public VideoMultipartUploadInitResponsePartsInner partNumber(Integer partNumber) {
    
    this.partNumber = partNumber;
    return this;
  }

   /**
   * part number
   * @return partNumber
  **/
  @javax.annotation.Nullable
  public Integer getPartNumber() {
    return partNumber;
  }


  public void setPartNumber(Integer partNumber) {
    this.partNumber = partNumber;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VideoMultipartUploadInitResponsePartsInner videoMultipartUploadInitResponsePartsInner = (VideoMultipartUploadInitResponsePartsInner) o;
    return Objects.equals(this.signedUrl, videoMultipartUploadInitResponsePartsInner.signedUrl) &&
        Objects.equals(this.partNumber, videoMultipartUploadInitResponsePartsInner.partNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(signedUrl, partNumber);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VideoMultipartUploadInitResponsePartsInner {\n");
    sb.append("    signedUrl: ").append(toIndentedString(signedUrl)).append("\n");
    sb.append("    partNumber: ").append(toIndentedString(partNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("signedUrl");
    openapiFields.add("PartNumber");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to VideoMultipartUploadInitResponsePartsInner
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!VideoMultipartUploadInitResponsePartsInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in VideoMultipartUploadInitResponsePartsInner is not found in the empty JSON string", VideoMultipartUploadInitResponsePartsInner.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!VideoMultipartUploadInitResponsePartsInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `VideoMultipartUploadInitResponsePartsInner` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("signedUrl") != null && !jsonObj.get("signedUrl").isJsonNull()) && !jsonObj.get("signedUrl").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `signedUrl` to be a primitive type in the JSON string but got `%s`", jsonObj.get("signedUrl").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!VideoMultipartUploadInitResponsePartsInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'VideoMultipartUploadInitResponsePartsInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<VideoMultipartUploadInitResponsePartsInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(VideoMultipartUploadInitResponsePartsInner.class));

       return (TypeAdapter<T>) new TypeAdapter<VideoMultipartUploadInitResponsePartsInner>() {
           @Override
           public void write(JsonWriter out, VideoMultipartUploadInitResponsePartsInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public VideoMultipartUploadInitResponsePartsInner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of VideoMultipartUploadInitResponsePartsInner given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of VideoMultipartUploadInitResponsePartsInner
  * @throws IOException if the JSON string is invalid with respect to VideoMultipartUploadInitResponsePartsInner
  */
  public static VideoMultipartUploadInitResponsePartsInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, VideoMultipartUploadInitResponsePartsInner.class);
  }

 /**
  * Convert an instance of VideoMultipartUploadInitResponsePartsInner to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

